# Enable plugin? true - yes, false - no
enable: true

#Token for discord. Get this for developers page.
token: "TOKEN"

# MESSAGES

#description for bot
description: "Bot for adding players to the whitelist"
rating_description: "This part of the bot allows you to give a rating to users!"
permissions_description: "This part of the bot allows you to give a permission to users!"

## PERMISSIONS

# Enable the granting of rights? true - yes, false - no
permissions: true

# The right to issue
permission_for_give: "chatty.chat.sendMessage"

# RATING

# # Enable the granting of rating? true - yes, false - no
rating: false

# A role that has the right to raise and lower the rating.
rating_DG_role: "1040256458190762095"